title: Carl Magnuson
logo: "/images/logo.png?raw=true"
description: >
  I'm a software developer based in Saint Paul, Minnesota.  I work primarly in Java but have experience in a number of languages and frameworks, and interests in functional programming, static analysis and powerful type systems.
  <br><br>
  I enjoy cooking, gardening, woodworking, and riding my road bike.
  <br><br>
  <a href="https://www.linkedin.com/in/carl-magnuson-8a05581b1">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
url: https://www.carlmagnuson.com
google_analytics: UA-175557391-1
