title: Carl Magnuson # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description
  <br><br>
  Second description
  <br><br>
  <a href="https://www.linkedin.com/in/carl-magnuson-8a05581b1">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
url: https://www.carlmagnuson.com
google_analytics: UA-175557391-1 # your Google Analytics tracking ID here
